-- ============================================================
-- 무해한 마을 — Supabase 테이블 생성 SQL
-- 사용법: Supabase 대시보드 → SQL Editor → 아래 전체 붙여넣기 → Run
-- 기존 AD-muhae-career 테이블 스타일(snake_case, text, boolean, timestamptz)을 따름
-- ============================================================

-- =========================
-- 1) 공모전 신청 (contest.html)
-- =========================
create table if not exists "AD-muhae-contest" (
  id               bigint generated by default as identity primary key,
  name             text,          -- 이름
  birth            text,          -- 생년월일
  university       text,          -- 학교/소속
  region           text,          -- 거주 지역
  residence_detail text,          -- 거주지 세부
  phone            text,          -- 연락처
  email            text,          -- 이메일
  category         text,          -- 참가 부문
  q1               text,          -- 질문1 답변
  q2               text,          -- 질문2 답변
  idea             text,          -- 구체화 아이디어
  portfolio_link   text,          -- 포트폴리오 링크
  status           text,          -- 현재 상태
  agree_privacy    boolean,       -- 개인정보 수집 동의
  agree_use        boolean,       -- 활용 동의
  agree_marketing  boolean,       -- 마케팅 수신 동의
  user_agent       text,          -- 접속 환경
  submitted_at     timestamptz,   -- 제출 시각(클라이언트)
  created_at       timestamptz default now()
);

alter table "AD-muhae-contest" enable row level security;

-- 익명(anon) 사용자가 INSERT만 가능하도록 허용
drop policy if exists "anon insert contest" on "AD-muhae-contest";
create policy "anon insert contest"
  on "AD-muhae-contest" for insert
  to anon
  with check (true);


-- =========================
-- 2) 1:1 신청 (apply.html)
-- =========================
create table if not exists "AD-muhae-apply" (
  id               bigint generated by default as identity primary key,
  name             text,          -- 이름
  age              text,          -- 나이
  phone            text,          -- 연락처
  region           text,          -- 거주 지역
  residence_detail text,          -- 거주지 세부
  status           text,          -- 현재 상태
  status_other     text,          -- 기타 상태 입력
  job_target       text,          -- 희망 직무/목표
  job_type         text,          -- 직무 유형
  edu              text,          -- 학력
  history          text,          -- 이력/경험
  motivation       text,          -- 참여 동기
  support          text,          -- 필요한 지원
  agree_privacy    boolean,       -- 개인정보 수집 동의
  user_agent       text,          -- 접속 환경
  submitted_at     timestamptz,   -- 제출 시각(클라이언트)
  created_at       timestamptz default now()
);

alter table "AD-muhae-apply" enable row level security;

-- 익명(anon) 사용자가 INSERT만 가능하도록 허용
drop policy if exists "anon insert apply" on "AD-muhae-apply";
create policy "anon insert apply"
  on "AD-muhae-apply" for insert
  to anon
  with check (true);


-- =========================
-- 3) 스타트업/창업 신청 (startup.html)
-- =========================
create table if not exists "AD-muhae-startup" (
  id               bigint generated by default as identity primary key,
  name             text,          -- 이름
  birth            text,          -- 생년월일
  university       text,          -- 학교/소속
  region           text,          -- 거주 지역
  residence_detail text,          -- 거주지 세부
  phone            text,          -- 연락처
  email            text,          -- 이메일
  q1               text,          -- 질문1 답변
  q2               text,          -- 질문2 답변
  interest         text,          -- 관심 분야(복수 선택)
  motivation       text,          -- 참여 동기
  hope             text,          -- 기대/희망 사항
  agree_privacy    boolean,       -- 개인정보 수집 동의
  agree_use        boolean,       -- 활용 동의
  user_agent       text,          -- 접속 환경
  submitted_at     timestamptz,   -- 제출 시각(클라이언트)
  created_at       timestamptz default now()
);

alter table "AD-muhae-startup" enable row level security;

-- 익명(anon) 사용자가 INSERT만 가능하도록 허용
drop policy if exists "anon insert startup" on "AD-muhae-startup";
create policy "anon insert startup"
  on "AD-muhae-startup" for insert
  to anon
  with check (true);
